@startuml
'https://plantuml.com/sequence-diagram

title Запрос рекомендации \nдля пользователя
actor User as user
participant API as api

database "DB \nAdapter" as db
participant Queue as queue
collections workers as handler
participant "DWH" as ext_api

user -> api++: запрос\nрекомендации
api -> db++: запрос\nрекомендации

alt рекомендация есть и\nона актуальна
    api <- db--: рекомендация
user <- api: рекомендация
else рекомендации нет или\nона не актуальна
    api -> ext_api++: получить популярные фильмы
    api <- ext_api--: популярные фильмы

    api -> queue++: обновить\nрекомендацию
    user <- api--: рекомендация

    queue -> handler--++: обновить\nрекомендацию
    handler -> ext_api++: получить данные\nо пользователе
    handler <- ext_api--: данные\nо пользователе
    handler -> handler: вжухх и\nрекомендация
    handler -> db--: сохранить рекомендацию
end

@enduml