services:
  ugc:
    build:
      context: .
    ports:
      - "8004:8000"
    networks:
      - praktikum
    command: python3 main.py

networks:
  praktikum:
    external: true
    name: praktikum
