services:

  elt-elk:
    env_file:
      - .env
    build: ./elastic
    networks:
      - praktikum
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./postgres/dbinit:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - praktikum

networks:
  praktikum:
    external: true
    name: praktikum